services:
  nginx:
    hostname: ${HOST_NAME}
    image: nginxboilerplate/nginx-boilerplate
    restart: always
    ports:
      - 80:80
      - 443:443
    # Removido o uso de secrets
    volumes:
      - ./path/to/your/nginx.conf:/etc/nginx.conf  
      - ./path/to/your/php:/var/www/html  
    networks:
      - monitoring_network

  fpm:
    image: umkus/nginx-boilerplate-php
    restart: always
    volumes:
      - ./path/to/your/php:/var/www/html  # Monte o mesmo diretório de arquivos PHP
    networks:
      - monitoring_network

  prometheus:
    image: prom/prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring_network

  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=your_admin_password  # Defina a senha do admin para o Grafana
    networks:
      - monitoring_network

# Removida a definição de secrets
networks:
  monitoring_network:
