name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker build -t my-web-app .

      - name: Run tests
        run: |
          docker run -d --name test-container -p 3000:3000 my-web-app
          sleep 10
          curl --fail http://localhost:3000 || exit 1
          docker stop test-container
          docker rm test-container
